import Head from "next/head";
import Navbar from "../../components/Navbar";
import SocialButton from "../../components/SocialButton";
import Dribble from '../../public/dribbble.svg'
import Instagram from '../../public/instagram.svg'
import Linkedin from  '../../public/linkedin.svg'
import ProjectPreview from "../../components/ProjectPreview";
import Github from "../../public/github.svg"
import Doc from "../../public/Doc.svg"
import SkillCard from "../../components/SkillCard";
import AboutMe from "../../components/AboutMe";
import PhotoGallery from "../../components/PhotoGallery";
import Experience from "../../components/Experience";
import { motion } from 'framer-motion';

const containerVariants = {
  hidden: { opacity: 0, x: -100 },
  visible: { opacity: 1, x: 0 },
};

const imageVariants = {
  hidden: { opacity: 0, scale: 0.8 },
  visible: { opacity: 1, scale: 1 },
};

const transition = {
  type: 'spring',
  stiffness: 100,
  damping: 10,
};

export default function Home() {

  return (
    <>
    
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      
      <section id="home" className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-6 mb-8 mt-4">
        <div className="h-[32rem] rounded-3xl p-12 flex flex-col justify-between animated-gradient bg-cover border-l-4 border-[#3D3A38]">
          <h1 className="text-5xl font-bold mb-4">Rayaan Khan <span className="block mt-2 text-4xl text-gray-700">Software Engineer</span></h1>
          <div className="mt-auto">
            <div className="flex flex-col lg:flex-row items-center gap-6 justify-self-end mb-4">
              <button className="bg-[#FF8B3D] text-white font-semibold py-3 px-12 rounded-full w-60 lg:w-auto hover:bg-[#FF5A5F] transition-all duration-300 shadow-lg hover:shadow-xl">Contact me</button>
              <div className="flex items-center gap-6">
                <SocialButton bgColor="github" link="https://github.com/rayaan-khan428">
                  <Github className="w-6 h-6" />
                </SocialButton>
                <SocialButton bgColor="linkedin" link="https://www.linkedin.com/in/rayaan-k/">
                  <Linkedin className="w-5 h-5" />
                </SocialButton>
                <SocialButton bgColor="dribble" link="https://docs.google.com/document/d/1d5cTvAW1e4MiQ92Y-gsn3pnisK_oi-_8/edit?usp=sharing&ouid=100819565910931085672&rtpof=true&sd=true">
                  <Doc className="w-5 h-5" />
                </SocialButton>
              </div>
            </div>
          </div>
        </div>
        <div className="h-[32rem] rounded-3xl p-8 bg-[url('/profile.jpg')] bg-cover bg-center shadow-xl hover:shadow-2xl transition-all duration-300 border-l-4 border-[#3D3A38] relative overflow-hidden">

        </div>
      </section>


      {/* hero banner section ends */}


      <section className="grid grid-cols-1 mb-8">
        <AboutMe />
      </section>

      <section id='experience' className="grid grid-cols-1 lg:grid-cols-1 gap-6 my-8 mb-12">
        <h2 className="text-4xl font-bold text-[#004777] mb-6">Work Experience</h2>
        
        <Experience
        companyName="Scotiabank"
        role="Software Engineer Intern"
        experiencePoints={[
          "Developed and maintained scalable financial applications using modern JavaScript frameworks and microservices architecture.",
          "Collaborated with cross-functional teams to implement new features and optimize user experience for banking applications.",
          "Participated in agile development processes, contributing to sprint planning, daily standups, and retrospectives."
        ]}
        dark={false}
        link="https://www.scotiabank.com/"
        logoSrc="https://logos-world.net/wp-content/uploads/2021/03/Scotiabank-Logo.png"
        />
        
        <Experience
        companyName="Thales"
        role="Software Engineer Intern"
        experiencePoints={[
          "Developed D-SPICO web-app for train safety monitoring and testing, participating in full-stack development.",
          "Worked with senior engineers to modify current D-SPICO application to adapt to requirements for Wayside Train Monitoring System.",
          "Documented and validated the compatibility and testing procedures between D-SPICO software and onboard train hardware, ensuring the safe operation of trains."
        ]}
        dark={false}
        link="https://www.thalesgroup.com/en"
        logoSrc="/thales_logo.png"
        />

        <Experience
        companyName="Dyne"
        role="Software Engineer Intern"
        experiencePoints={[
          "Utilized Selenium effectively to collect comprehensive data from over 3000+ real estate listings",
          "Reduced scraping time by 2 minutes per listing, by optimizing the code with multi-threading techniques.",
          "Engineered an application utilizing Places API, tailored for restaurant information retrieval."
        ]}
        dark={false}
        link="https://www.dyneapp.ca/"
        logoSrc="https://yt3.googleusercontent.com/IRELTnzuPx1Ynr_I70Wq-AwIiNFS7WYZ7ORmWW-MhydGPA_eU4KhXmO7V2aMYZbYYuEXqFmd6A=s900-c-k-c0x00ffffff-no-rj"
        />
      </section>

      <section id="projects" className="grid grid-cols-1 lg:grid-cols-2 gap-6 my-8">
        <h2 className="text-4xl font-bold text-[#004777] mb-6 col-span-full">Projects</h2>

          <ProjectPreview
          name="Leetr"
          description="Save time & Prepare effectively "
          imageUrl="/project-1.png"
          bgColor="#252525"
          dark
          link="https://research2-slides-front-end.vercel.app/"
        />      

        
        <ProjectPreview
          name="Huberman AI"
          description="Get scientifically accurate answers"
          imageUrl="/project-2.png"
          bgColor="#252525"
          dark
          link="https://research2-slides-front-end.vercel.app/"
        />
        <ProjectPreview
          name="Airport Management System"
          description="Manage all aspects of an airport"
          imageUrl="/project-3.png"
          bgColor="#252525"
          dark
          link="https://github.com/Rayaan-khan428/Airline-Management-System"
          
        />
        <ProjectPreview
          name="Research2Slides"
          description="Convert research papers to powerpoints!"
          imageUrl="/project-4.png"
          bgColor="#252525"
          dark
          link="https://research2-slides-front-end.vercel.app/"
        />
      </section>

      {/* Skills */}
      <section id="skills" className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12 mt-12">
        <h2 className="text-4xl font-bold text-[#004777] mb-6 col-span-full">Skills & Interests</h2>
        <SkillCard
          title="Tech Stack"
          items={[
            'Python', 'Java', 'JavaScript', 'TypeScript', 'HTML/CSS', 'C', 'Unity',
            'NextJS', 'ExpressJS', 'React', 'NodeJS', 'SQL', 'MongoDB'
          ]}
        />
        <SkillCard
          title="Tools"
          items={[
            'Git and Github', 'Tableau', 'PowerBI', 'UML', 'Maven', 'Firebase',
            'Googling', 'Linux', 'PostgreSQL', 'Spring Boot', 'Selenium', 'R'
          ]}
        />
        <SkillCard
          title="Interests"
          items={[
            'Hackathons', 'Robotics', 'Weightlifting', 'Camping', 'Hiking',
            'Aviation & Aerospace', 'Machine learning & AI', 'Cooking'
          ]}
        />
      </section>
      
      <section id="photos" className="mb-12 mt-12">
        <h2 className="text-4xl font-bold text-[#004777] mb-6">Photography</h2>
        <PhotoGallery/>
      </section>
      

      {/* footer section */}
      <section id="contact" className="grid grid-cols-1 mb-12">
        <div className="min-h-[30rem] rounded-3xl p-12 flex flex-col gap-12 animated-gradient bg-cover border-l-4 border-[#3D3A38] shadow-xl">
          <h1 className="text-5xl font-bold">Want to work together?</h1>
          <p className="flex-1 text-lg">Feel free to reach out to collaborate on something or just say hello! <br/><span className="font-semibold mt-4 block">rayaan.k.ca@gmail.com</span>
          </p>

          <div className="flex flex-col lg:flex-row items-center gap-6 justify-self-end">
            <button className="bg-[#FF8B3D] text-white font-semibold py-3 px-12 rounded-full w-60 lg:w-auto hover:bg-[#FF5A5F] transition-all duration-300 shadow-lg hover:shadow-xl">Contact me</button>
            <div className="flex items-center gap-6">
              
              <SocialButton bgColor="github" link="https://github.com/Rayaan-khan428">
                <Github className="w-6 h-6"/>
              </SocialButton>

              <SocialButton bgColor="linkedin" link="https://www.linkedin.com/in/rayaan-k/">
                <Linkedin className="w-5 h-5"/>
              </SocialButton>
            </div>
          </div>
        </div>
      </section>  
    </>
  );
}
